### ISSUE TITLE
Pouvoir afficher une liste de randonnées

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-widget#1]
Pour cela il faut que l'utilisateur puisse rentrer une URL d'API Geotrek. Cette url pourra parfois être filtrée avec un portail. Par exemple :

https://demo-admin.geotrek.fr/api/v2/trek/

https://geotrekdemo.ecrins-parcnational.fr/api/v2/trek/?portals=2

**Comment by camillemonchicourt** [comment]
On pourrait imaginer d'utiliser d'autres filtres dans ce qu'on disait sur le besoin initial
Par exemple limiter à 1 ou plusieurs pratiques, à une structure, 1 ou plusieurs communes, etc...
Ce sera aussi possible de la même manière au moment où on définit l'URL de l'API, j'imagine ?

**Comment by thomaspnrhj** [comment]
Oui je pense aussi que l'on doit pouvoir filtrer sur d'autres filtres (à minima pratique et structure aussi) et pas uniquement le portail, Le portail c'est notre fonctionnement spécifique.

**Comment by bastyen** [comment]
#14
