### ISSUE TITLE
Widget d'une seule rando

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-widget#101]
Il a été évoqué plusieurs fois le fait de pouvoir générer un widget contenant la fiche d'un seul objet (une rando, un service, un site outdoor) sans la partie recherche.
Cette possibilité n'est actuellement pas documentée dans le constructeur de widget, mais le découpage du widget en composant depuis le départ le permet.

Exemple de widget avec la fiche détail d'une rando : 

```
<grw-trek-provider
  api="https://randoadmin.parc-haut-jura.fr/api/v2/"
  languages="fr"
  trek-id="242872"
> 
</grw-trek-provider>
<grw-trek-detail></grw-trek-detail>
```

Exemple de widget avec la fiche détail et la carte d'une rando (à mettre mieux en forme) : 

```
<grw-trek-provider api="https://randoadmin.parc-haut-jura.fr/api/v2/" languages="fr" trek-id="242872"></grw-trek-provider>
    <div style="width: 100vw; height: 800px"><grw-trek-detail></grw-trek-detail></div>
    <div style="width: 100vw; height: 800px">
      <grw-map
        name-layer="IGN"
        url-layer="https://data.geopf.fr/wmts?SERVICE=WMTS&amp;REQUEST=GetTile&amp;VERSION=1.0.0&amp;LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&amp;STYLE=normal&amp;FORMAT=image/png&amp;TILEMATRIXSET=PM&amp;TILEMATRIX={z}&amp;TILEROW={y}&amp;TILECOL={x}"
        attribution-layer="IGN"
      ></grw-map>
    </div>
```

**Comment by gbvt** [comment]
Bonjour, j'ai testé ce code sur une randonnée du CD06, mais je trouve quelques petits soucis dans cette disposition :
* la carte de la randonnée n'est pas auto-zoomée sur l'emprise itinéraire
* une div map-loader-container vient s'ajouter sous le profil de dénivelé, qui prend beaucoup de hauteur et s'affiche en permanence
* en console, il y a 2 erreur JS qui remontent, notamment sur onfullscreenchange et layerControlInputs

![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/2d15ecfe-8113-4dd7-9a42-1114f30c5621)

![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/09146536-c120-4527-acc7-3f3eed867af5)

**Comment by camillemonchicourt** [comment]
Oui, le widget a découpé en composants.
Mais son usage n'a été travaillé et optimise que pour le widget complet.
Il serait intéressant que le widget d'une seule rando combinant fiche et carte soit plus travaillé et facilement intégrable, mais cela nécessite des développements qui n'ont pas été priorisés jusque là.

**Comment by bastyen** [comment]
Peux-tu écrire le code html que tu utilises pour cet affichage ?

**Comment by bastyen** [comment]
Je viens de regarder.
C'est l'erreur liée à layerControlInputs qui empêche d'avoir le comportement attendu.
Celle-ci est déjà corrigé mais pas disponible sur la dernière version.
Ça sera donc corrigé lors de la prochaine release.

**Comment by bastyen** [comment]
En attendant, il est possible d'éviter cette erreur en utilisant

```
<grw-map
        name-layer="IGN,IGN"
        url-layer="https://data.geopf.fr/wmts?SERVICE=WMTS&amp;REQUEST=GetTile&amp;VERSION=1.0.0&amp;LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&amp;STYLE=normal&amp;FORMAT=image/png&amp;TILEMATRIXSET=PM&amp;TILEMATRIX={z}&amp;TILEROW={y}&amp;TILECOL={x},https://data.geopf.fr/wmts?SERVICE=WMTS&amp;REQUEST=GetTile&amp;VERSION=1.0.0&amp;LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&amp;STYLE=normal&amp;FORMAT=image/png&amp;TILEMATRIXSET=PM&amp;TILEMATRIX={z}&amp;TILEROW={y}&amp;TILECOL={x}"
        attribution-layer="IGN,IGN"
></grw-map>
```

**Comment by gbvt** [comment]
En effet, je valide pour ce mini correctif. Merci Bastien !

**Comment by camillemonchicourt** [comment]
Les composants indépendants ont été bien améliorés dans la version 0.18.0.
Et la documentation des différents composants vient d'être ajoutée. 
Exemple du composant d'une seule rando : https://geotrek-rando-widget.readthedocs.io/latest/documentation/data-provider/grw-trek-provider.html
