### ISSUE TITLE
Pouvoir surcharger des traductions

### ISSUE THREAD

**Issue by bruhnild** [GeotrekCE/Geotrek-rando-widget#122]
Il serait intéressant de pouvoir surcharger des traductions présentes dans le fichier [/src/i18n/i18n.ts](https://github.com/GeotrekCE/Geotrek-rando-widget/blob/main/src/i18n/i18n.ts#L128) afin de renommer certaines sections de la fiche détails d'un trek par exemple.

**Comment by bastyen** [comment]
C'est disponible à partir de la version 0.16.0.

Ce n'est pas encore documenté.

Il faut ajouter, par exemple, sur la page où est intégré un composant grw :

```
<script>
  window.grwTranslate = {
    fr: {
      options: {
        recommendations: "Nouvelle traduction"
        },
      recommendations: "Nouvelle traduction"
    },
  };
</script>
```

Il faut se baser sur ce fichier : https://github.com/GeotrekCE/Geotrek-rando-widget/blob/main/src/i18n/i18n.ts
