### ISSUE TITLE
Mieux organiser la section Recommandations

### ISSUE THREAD

**Issue by gbvt** [GeotrekCE/Geotrek-rando-widget#127]
Sur le Widget au détail d'une randonnée, la section nommée Recommandations semble être un regroupement de plusieurs informations distinctes de l'Admin. Dans nos tests, nous voyons en effet le bloc de recommandations (en rouge sur ma capture), mais aussi les étiquettes.
Au CD06, nous utilisons les étiquettes pour catégoriser les itinéraires par guide, secteur etc... et donc plutôt dans une optique de filtre et de classification des itinéraires.
Côté usager, le fait de les remonter comme "Recommandations" ne semble pas vraiment pertinent. Il serait intéressant d'étudier comment mieux présenter ces détails. A moins que nous ayons confondu l'utilisation des étiquettes, et des thèmes ?

![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/6b821881-540a-474d-98f3-d1a19ef1ec40)

**Comment by camillemonchicourt** [comment]
Oui, à la base, on a créé les "étiquettes" pour des infos complémentaires au champs texte "Recommandation", mais de manière plus structurée et globale.

Donc, dans Geotrek-rando-v3, on a en effet regroupé le champs "Recommandation" avec les étiquettes, comme on voit ici : 

![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/4418840/fd39cc2a-9ee5-45cf-a826-5df0d1882244)

Après, c'est vrai que les étiquettes est un concept très générique, qui peut être utilisé pour autre chose.
Mais je vois pas trop dans quel autre bloc on pourrait le mettre, car on ne peut pas non plus avoir un bloc "Étiquettes" car c'est un terme générique et technique, mais pas pour les utilisateurs.

Ce qu'on peut imaginer, c'est mettre ça dans un bloc plus global, nommé "Infos pratiques", ce qui est d'ailleurs le cas dans Geotrek-rando-v3.

A préciser, clarifier pour trouver le bon vocabulaire et groupes et noms de blocs, pour rester générique mais clair.

**Comment by bastyen** [comment]
Donc, on peut mettre les étiquettes dans une section unique avec "Infos pratiques", par défaut, comme titre.
Ensuite libre à l'utilisateur de [renommer](https://github.com/GeotrekCE/Geotrek-rando-widget/issues/122) la section.

**Comment by camillemonchicourt** [comment]
Oui je pense que le bloc global devrait être "Infos pratiques".
A voir par ailleurs si il faut remettre le sous-titre "Recommandation" juste pour le champs dédié.

**Comment by bastyen** [comment]
J'imagine qu'on laisse comme ça alors.
Je ferme l'issue mais on pourra de nouveau l'ouvrir si le besoin de créer une section unique pour les recommandations se fait ressentir.
