### ISSUE TITLE
Gestion de cache dans le widget ? (a étudier)

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-widget#13]

**Comment by camillemonchicourt** [comment]
C'est vrai qu'au niveau de Geotrek-rando, on met en cache serveur (NodeJS) toutes les infos annexes qui sont appelées en permanence (types de pratiques, niveau de difficulté, noms des communes) pour ne pas appeler l'API à chaque fois.

**Comment by bastyen** [comment]
Le navigateur gère lui-même cache.
