### ISSUE TITLE
Image par URL non chargée sur le widget

### ISSUE THREAD

**Issue by gbvt** [GeotrekCE/Geotrek-rando-widget#134]
Lorsque l'image d'un site outdoor est renseignée par une URL externe, celle-ci ne semble pas s'afficher dans le widget. Dans le code source, on voit que l'attribut SRC de l'image n'est en effet pas renseignée.

![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/d8546787-7d59-4b28-86e9-8a47e27a0b03)

![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/36d13239-fe2c-4fbf-93c1-6c45e56e224b)

**Comment by babastienne** [comment]
En effet je confirme que je reproduis le problème. Pourtant l'API renvoi bien l'URL de l'image, c'est donc bien un problème côté Widget. @bastyen ?

**Comment by bastyen** [comment]
Pas totalement.
On affiche le thumbnail hors il est égale à "". J'imagine que c'est le toujours le cas quand c'est une url externe ?
Dans ce cas, je peux vérifier si le thumbnail est renseigné avant de l'utiliser et si ce n'est pas le cas, j'utilise l'url.

**Comment by babastienne** [comment]
> J'imagine que c'est le toujours le cas quand c'est une url externe ? 

En effet, si lien externe alors Geotrek ne génère pas de thumbnail donc le champ sera vide

**Comment by bastyen** [comment]
https://github.com/GeotrekCE/Geotrek-rando-widget/releases/tag/0.19.0
