### ISSUE TITLE
Part CSS à ajouter Trek Detail

### ISSUE THREAD

**Issue by gbvt** [GeotrekCE/Geotrek-rando-widget#140]
Certaines parts HTML / CSS ne sont pas accessibles, il faudrait les ajouter pour avoir avoir une charte graphique harmonisée. A ce jour j'ai noté :
* sur le widget Trek Detail : les boutons de téléchargement GPX, PDF... Ce sont des balises **a dans la part "links-container"**
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/50d0c98a-869c-48a9-b4b7-fa04bee681a7)

* sur le widget Trek Detail : la couleur des numéros sur la Description. Ce sont des balises **ol li ::before dans la part "description"**
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/67f30eb7-83eb-456c-8467-0461cb4de99f)

L'idéal serait de pouvoir rendre les boutons carrés (radius) à même titre que le bouton "Rendre disponible hors ligne"
Et avoir la même couleur pour les numéros que la ligne en 2nd plan (ex : --color-primary-app)

**Comment by gbvt** [comment]
Petite note : le border-radius peut être géré via la variable globale CSS --border-radius, ce qui est une excellente chose pour avoir une homogénéité dans tout le site ! Nous l'avons géré comme ca, plutôt que chercher la part qui n'existe pas encore.

Toutefois, la couleur des chiffres du "pas à pas" ne semble pas contrôlée par une variable CSS, mais une valeur en dur : rgb(240, 65, 65)
Ce serait plus simple à avoir une variable de couleur, comme tout le reste des éléments du widget.

**Comment by bastyen** [comment]
Lors de la prochaine release, trois nouvelles parts seront disponibles `download-kml-button`, `download-gpx-button` et `download-pdf-button`.

Ainsi que deux nouvelles variables globales CSS `--description-step-color` et `--description-step-background-color`.

**Comment by gbvt** [comment]
Merci du dev, très pratique ! Par contre, il me semble que les noms des variables ont changé depuis ta dernière réponse. J'ai noté :
--reference-point-background-color (couleur du cercle)
--reference-point-color (couleur du texte)

Ca fonctionne bien !
![image](https://github.com/user-attachments/assets/0832c8d3-0b26-497b-bb4c-e7054ae92bdb)

**Comment by bastyen** [comment]
Effectivement, c'est bien `--reference-point-color` et `--reference-point-background-color`.
