### ISSUE TITLE
Gestion de la hauteur du dénivelé dans Trek Map

### ISSUE THREAD

**Issue by gbvt** [GeotrekCE/Geotrek-rando-widget#141]
Sur le widget Trek Map, le bloc HTML et ses paramètres de taille semblent contrôler l'intégralité carte + dénivelé.
Il serait intéressant de pouvoir contrôler la hauteur du dénivelé relativement au bloc complet, on dirait que c'est forcément 50% de la hauteur du canvas, quel que soit l'appareil utilisé.

Sur écran d'ordinateur, c'est raisonnable :
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/5904ca84-da8d-4ef9-8d9c-1288f7e7017d)

Mais sur mobile, cela devient trop haut et exagéré :
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/d335e7dc-e1ec-4915-9e31-5c1786dbe8d3)

**Comment by bastyen** [comment]
Donc, il faudrait que la hauteur du profil altimétrique soit moins grande sur mobile, enfin plutôt avoir un meilleur ratio hauteur-largeur selon la taille de l'écran.

**Comment by bastyen** [comment]
Après le prochain déploiement, il sera possible de modifier les valeurs suivantes : elevation-height et mobile-elevation-height, 280px par défaut pour les deux.
Chacune définie la hauteur, en pixel, du profil altimétrique selon la largeur de conteneur. Celle-ci est définie par large-view-size, elle aussi modifiable, 1024px par défaut.

Il faut les définir avec le nombre donc par exemple mobile-elevation-height="180"

**Comment by gbvt** [comment]
Merci ! On teste sous peu dans notre intégration au site web.
