### ISSUE TITLE
Taille des icones sur carte

### ISSUE THREAD

**Issue by gbvt** [GeotrekCE/Geotrek-rando-widget#142]
Y a-t-il une variable qui permette de controler la taille / le radius des icones sur le Widget carte, afin de le rentre plus lisible ?
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/31708825/1d64d1a4-9e55-4ae7-a544-9234aa2fdc4c)

**Comment by bastyen** [comment]
Si je comprends bien, l'idée est de pouvoir contrôler finement le marqueur en permettant de changer sa taille et son radius correspondant ici au rond vert ainsi que la taille de l'icône ?

**Comment by camillemonchicourt** [comment]
Je pense qu'il vaut mieux ajuster ça de base pour tous dans le widget et ne pas faire des paramètres pour ce genre de petites choses.
En effet, il faut certainement revoir les valeurs pour tous pour que la taille et le style soit plus lisible, comme c'est le cas dans GTR, où chacun n'a pas besoin de modifier ces éléments.

**Comment by bastyen** [comment]
Lors du prochain déploiement, ça sera personnalisable.

Il est possible de gérer la taille des marqueurs avec `main-marker-size`, `selected-main-marker-size`, `main-cluster-size`, `common-marker-size`, `common-marker-size`, `departure-arrival-marker-size` et `point-reference-marker-size`. Les valeurs par défaut n'ont pas changé et sont visibles ici : https://github.com/GeotrekCE/Geotrek-rando-widget/tree/main/src/components/grw-map

De plus, il est possible d'influer sur la taille des icônes avec les variables css globales suivantes : `--main-marker-icon-width` et `--common-marker-icon-width`. Elles prennent par défaut 80% de la largeur et la hauteur s'adapte automatiquement.

Je précise que des parts existent aussi afin de changer d'autres options, comme le radius.

Il faudra qu'on pense à documenter cette partie @bruhnild
