### ISSUE TITLE
Affichage des signalétiques sur la carte Widget

### ISSUE THREAD

**Issue by gbvt** [GeotrekCE/Geotrek-rando-widget#143]
Cette fonctionnalité très importante a été demandée au début du projet avec le CD06 : avoir la couche des Signalétiques dans le widget carte, si possible affichée par défaut. Cela est impératif afin de pouvoir guider l'usager final sur le terrain.

**Comment by bastyen** [comment]
La couche signalétiques sera ajoutée. Elle sera désactivée par défaut pour ne pas influer sur les grw déjà déployés. Par contre, elle sera affichéee par défaut si elle est activé. Un paramètre sera donc ajouté.

**Comment by bastyen** [comment]
Il est possible d'ajouter `signages="true"` pour `grw-app` et `grw-trek-provider`
