### ISSUE TITLE
Affichage du fond de carte manquant.

### ISSUE THREAD

**Issue by fs-leo** [GeotrekCE/Geotrek-rando-widget#159]
Bonjour, 

Je remarque que sur un widget donné les fonds de carte ne s'affichent pas. Cela semble venir du site https://wxs.ign.fr/ qui n'est pas accessible.
Je vous joins le code du widget donné ainsi que la capture de la console :
```
<script type="text/javascript" src="https://rando-widget.geotrek.fr/latest/dist/geotrek-rando-widget/geotrek-rando-widget.js"></script>
<p><grw-app api="https://openig-gag-cd48.ataraxie.fr/api/v2/" attribution-layer="&lt;a target='_blank'  data-cke-saved-href='https://ign.fr/' href='https://ign.fr/'&gt;IGN&lt;/a&gt;" cities="48019,48050,48166,48061,48065,48069,48146,48074,48075,48088,48085,48131,48028,48141,48096,48130,48176,48193,48036" color-arrival-icon="#85003b" color-background="#FFFFFF" color-departure-icon="#006b3b" color-on-primary="#ffffff" color-on-primary-container="#FFFFFF" color-on-secondary-container="#FFFFFF" color-on-surface="#1c1b1f" color-on-surface-variant="##21005e" color-poi-icon="#006c9b" color-primary-app="#006c9b" color-primary-container="#ED8B00" color-secondary-container="#006c9b" color-sensitive-area="#006c9b" color-surface="#ED8B00" color-surface-container-high="#FFF8F0" color-surface-container-low="#FFF8F0" color-surface-variant="#ffffff" color-trek-line="#006c9b" fab-background-color="#eaddff" fab-color="#21005d" languages="fr" name-layer="IGN" practices="8" url-layer="https://wxs.ign.fr/cartes/geoportail/wmts?&amp;REQUEST=GetTile&amp;SERVICE=WMTS&amp;VERSION=1.0.0&amp;STYLE=normal&amp;TILEMATRIXSET=PM&amp;FORMAT=image/png&amp;LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&amp;TILEMATRIX={z}&amp;TILEROW={y}&amp;TILECOL={x}"></grw-app></p>
```

![image](https://github.com/user-attachments/assets/d494023c-53e3-41ed-a546-527310affe93)

Merci.

**Comment by babastienne** [comment]
Bonjour @fs-leo :wave: 

En effet je pense qu'il faut modifier le code de votre widget pour utiliser le fond de plan IGN qui fonctionne.
En regardant l'url actuelle il me semble que vous utilisez une vieille version qui n'est plus maintenue depuis la migration de 2023 effectuée par l'IGN.

Pour plus d'infos voir cet article : https://makina-corpus.com/logiciel-libre/bascule-ign-tutoriel-modification-fonds-plan-geotrek

Je pense qu'il faudrait modifier le paramètre `url-layer` pour mettre dedans la valeur suivante : `https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&STYLE=normal&FORMAT=image/png&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}`

A tester et vérifier de votre côté ?
