### ISSUE TITLE
La vue Liste doit pouvoir afficher à gauche les éléments essentiels d'une randonnée et à droite une carte avec le point de départ de chaque randonnée sur la carte

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-widget#2]
Suggestions de designs :

Sur PC ecran medium
![image](https://user-images.githubusercontent.com/16348048/173042301-1c2c54af-e6fc-4010-9822-fb52b683653d.png)

Sur PC ecran large
![image](https://user-images.githubusercontent.com/16348048/173042398-f9a2b901-38e1-4156-bf28-205da2bf5ee1.png)

Sur smartphone on affiche uniquement la liste des objets et pas la vue carte pour le moment
![image](https://user-images.githubusercontent.com/16348048/173042532-f88a3707-1de2-4b0d-9f6d-190153038c85.png)

A terme on pourrait imaginer une manière de switcher entre la vue liste et carte sur smartphone (#3 )

**Comment by camillemonchicourt** [comment]
De tout ce que j'ai pu voir, les sites des OT sont rarement sur 100% de largeur et ont en plus parfois une petite colonne de contenu à droite.
C'est pourquoi je pense que partir sur un fonctionnement avec une liste à gauche et une carte à droite ne sera pas adaptée dans de nombreux cas selon moi.

C'est pourquoi le widget Cirkwi est basée sur une carte au-dessus de la liste.

Voir 2 exemples d'intégration : 
- https://www.pays-bergerac-tourisme.com/fr/a-voir-a-faire/randonnees/a-vtt
- https://www.izoard-tourisme.fr/en-ete/toutes-les-randonnees

Mais à discuter car vous avez peut-être une autre analyse des contextes d'intégration.

**Comment by camillemonchicourt** [comment]
A ne pas oublier sur les cards de la liste : le picto de la pratique du contenu

**Comment by camillemonchicourt** [comment]
Ce n'est pas qui veulent pas, mais que leur site ne permet pas d'occuper 100% de largeur.

C'est par exemple le cas de votre site : http://www.parc-haut-jura.fr/fr/rubriques-editoriales/la-maison-du-parc/decouvrez-la-maison-du-parc.882-266__2051.php

Et dans le cas de votre site, c'est encore plus contraignant car il fort possible que le bloc de droite (Actualités, Tout savoir) soit fixe et permanent.
Le site du PNE c'est pareil : https://www.ecrins-parcnational.fr/patrimoine/lapollon
Et plein d'OT sont dans ce cas, c'est pourquoi je suis réservé sur l'idée d'un widget qui nécessite 100% de largeur, ça en limiterait l'usage.
