### ISSUE TITLE
Ressource javascript non disponible pour les navigateurs qui ne prennent pas en charge ESM.

### ISSUE THREAD

**Issue by seegwen** [GeotrekCE/Geotrek-rando-widget#26]
En intégrant le widget dans un site, je tente de récupérer les sources js depuis UNPKG pour les héberger avec le site.

D'après le [README](https://github.com/GeotrekCE/Geotrek-rando-widget/blob/main/readme.md) du repo, il y a deux fichiers javascript à linker dans la page qui va accueillir le widget:

Le premier pour les navigateurs qui prennent en charge ESM:
https://unpkg.com/@geotrekce/geotrek-rando-widget@latest/dist/geotrek-rando-widget/geotrek-rando-widget.esm.js
=> la requête est OK

Le deuxième pour les legacy browsers:
https://unpkg.com/@geotrekce/geotrek-rando-widget@latest/dist/geotrek-rando-widget/geotrek-rando-widget.js
La la requête renvoie un `Cannot find "/dist/geotrek-rando-widget/geotrek-rando-widget.js" in @geotrekce/geotrek-rando-widget@0.0.11`

Si cela est normal, peut-être qu'il faut supprimer la mention inutile dans le README.

**Comment by bastyen** [comment]
Effectivement, le fichier n'existait pas. Il est disponible à partir de la 0.0.12.

**Comment by seegwen** [comment]
Checkout out, built, OK. Il faut vraiment que je me mette à apprendre ces processus de publication...

Merci @bastyen 👍
