### ISSUE TITLE
Gestion multi-langue

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-rando-widget#28]
Actuellement, quand on configure le widget, on spécifie une seule langue.
Il serait intéressant de pouvoir proposer plusieurs langues, avec la possibilité pour l'utilisateur de basculer sur une langue ou une autre, voire de s'appuyer sur la langue du navigateur pour proposer le contenu en FR, EN, IT ou autre selon la langue.

Attention cependant, certaines randos sont publiées dans une langue mais pas les autres, si pas encore traduite dans la langue en question.

- [x] Possibilité de renseigner plusieurs langues dans la configuration du
widget
- [x] Si plusieurs langues renseignées, un bouton apparaît dans le header de
l’app pour basculer d’une langue à l’autre

**Comment by bastyen** [comment]
On peut ajouter un sélecteur de langue pour le widget app mais il doit être possible de ne pas l'afficher dans le cas où le basculement de langue est déjà présent en amont ou bien lorsqu'il n'y a qu'une seule langue disponible.

**Comment by camillemonchicourt** [comment]
Oui, on pourrait définir qu'une seule langue, ou plusieurs. 
Si une seule langue est définie en paramètre, alors on n'affiche pas de sélecteur de langue.
C'est ce qu'on fait dans Geotrek-rando-v3.
On a aussi défini une langue par défaut, dans le cas où la langue du navigateur n'est pas proposé par le widget, pour savoir quelle langue structurer dans ce cas.
Config de Geotrek-rando-v3 - https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/config/header.json#L5-L6

**Comment by bastyen** [comment]
Les nouvelles traductions peuvent être ajoutées dans ce fichier : https://github.com/GeotrekCE/Geotrek-rando-widget/blob/main/src/i18n/i18n.ts

**Comment by bastyen** [comment]
- [ ] Afficher de nouveau le sélecteur de langue lorsqu'il y en plus d'une renseignée.
