### ISSUE TITLE
Problème CSS - Titre rando

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-rando-widget#29]
Lors de l'ouverture d'une fiche rando, le texte du titre de la rando se chevauche : 
![image](https://user-images.githubusercontent.com/19687397/202403131-ad3a13f9-e6f1-4a5f-a3b3-452fd2d74209.png)
![image](https://user-images.githubusercontent.com/19687397/202403157-d045d612-0232-4696-996e-8233557da686.png)

**Comment by bastyen** [comment]
Bonjour,

C'est déjà corrigé depuis la 0.0.15.

**Comment by camillemonchicourt** [comment]
Salut, peut-être que le widget a été intégré avec une version fixe du widget dans le code d'appel de celui-ci et que du coup vous n'avez pas la nouvelle version en ligne ?

**Comment by bastyen** [comment]
Oui, il est en 0.0.14.

**Comment by thomaspnrhj** [comment]
Ok j'avait pas fait gaffe, ok je transmet au prestataire de l'office du tourisme.
Ca veut dire qu'à chaque nouvelle version il faut modifier le code d'appel ?
Et dernière question, pourquoi on est encore sur une V0, il y a des devs en attente encore pour passer sur une version officielle ?

**Comment by bastyen** [comment]
On pourrait passer en 1.0.0 mais je préfère attendre que tout soit stabilité comme par exemple, la façon dont on fournit le widget.

Actuellement, il faut modifier le code de version ou mettre @latest à la place de celui-ci pour que ce soit automatique mais ça serait encore moins performant.

**Comment by thomaspnrhj** [comment]
Ok merci de ces précisions !
