### ISSUE TITLE
Sur Smartphone  dans la vue liste, pouvoir switcher entre la carte et la liste

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-widget#3]

**Comment by camillemonchicourt** [comment]
Même en web, je partirai plutôt sur une carte au-dessus de la liste, qui pourrait aussi fonctionner en mobile.
Voir https://www.pays-bergerac-tourisme.com/fr/a-voir-a-faire/randonnees/a-vtt

Mais en effet le switch entre carte et liste est sympa aussi en mobile.
