### ISSUE TITLE
Filtre et recherche

### ISSUE THREAD

**Issue by bastyen** [GeotrekCE/Geotrek-rando-widget#37]
- [x] Possibilité de filtrer par contenu textuel
- [x] Ajout des filtres type de parcours,
longueur, dénivelé, accessibilité, labels, thèmes, communes
- [x] Changer l'interface des filtres pour permettre de filtrer par
grande catégorie : création de sous-menus permettant de différencier les filtres liés à un type d’objet précis
des filtres communs à tous les objets
- [x] Ajout d’un bouton « Tout effacer » pour supprimer les filtres sélectionnés

**Comment by babastienne** [comment]
@bastyen il est désormais possible de récupérer les informations de dsictricts sur les endpoints qui contiennent déjà "cities" dans l'API V2. (https://github.com/GeotrekCE/Geotrek-admin/pull/3633)

Valable depuis la release 2.99.0 de Geotrek-Admin
