### ISSUE TITLE
Amélioration des POI

### ISSUE THREAD

**Issue by bastyen** [GeotrekCE/Geotrek-rando-widget#39]
- [x] Refonte du design des tuiles de POI pour limiter leur taille 
- [x] Conteneurisation des tuiles de POIs dans un élément à la hauteur
limitée, dans lequel il sera possible de scroller
- [x] Bouton « Lire plus »
- [x] Lorsqu’on clique sur la photo d’un POI, possibilité d’afficher l’image en
plein écran
- [x] Possibilité d’afficher plusieurs images par POI
- [x] Modification du titre du bloc de POIs et affichage du nombre d’objets
dans le titre
- [x] Affichage de l’icône de la catégorie du POI sur sa vignette

**Comment by MatthieuClemot** [comment]
Le bouton "Lire plus" ne semble pas apparaitre, ou du moins n'est pas visible de manière claire

**Comment by bastyen** [comment]
Je viens de regarder et le bouton "Lire plus" est bien visible.
Pouvez-vous me fournir une capture d'écran ?

**Comment by MatthieuClemot** [comment]
Le bouton est finalement bien visible après vérification, je ne sais pas pourquoi il ne l'était pas sur mon poste la semaine dernière.
