### ISSUE TITLE
Formatage de texte particulier

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-widget#52]
Sur cet exemple : 

![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/16348048/98f2cff4-6437-4ed7-8848-ff6f16e88ca9)

[LIEN VERS L'EXEMPLE](https://demo-rando-widget.geotrek.fr/desktop.html?trek=224737)

Est-ce normal ou pas ?

**Comment by camillemonchicourt** [comment]
Pour éviter les styles venant de HTML contenant des styles bizarres, dans Geotrek-rando-v3, on nettoie le code HTML reçu de l'API, mais en gardant les balises de mise en forme (gras, italique, souligné, couleurs, images...).
Un peu galère et ça a mis un peu de temps à caler, mais ça permet d'avoir un texte toujours plus propre.

Mais dans ce cas, le soucis ne semble pas venir du HTML, car celui-ci est OK : https://randonature.parc-haut-jura.fr/trek/224737-Tour-des-Roches-d-Orvaz---39B
Mais bien d'un soucis de CSS du widget qui ajoute sur ce bloc la police `Material Symbols Outlined`.
