### ISSUE TITLE
Parametre language non pris en compte

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-rando-widget#56]
Le paramètre `language` ne semble pas pris en compte.
Version testée 0.3.6

﻿
<img width="559" alt="Capture d’écran 2023-10-31 à 11 49 37" src="https://github.com/GeotrekCE/Geotrek-rando-widget/assets/44799642/8c410416-1257-47d3-a86a-57a9ddc80c09">
﻿
<img width="1173" alt="Capture d’écran 2023-10-31 à 11 50 01" src="https://github.com/GeotrekCE/Geotrek-rando-widget/assets/44799642/7ccb2cc2-a39c-4094-a599-f1ef6b2350db">

**Comment by bastyen** [comment]
Merci.
Le paramètre est maintenant `languages`. On peut renseigner une ou plusieurs langues séparées par des ",". Si on a plus d'une langue, un sélecteur s'affiche.
Je vais mettre à jour le Storybook.

**Comment by bastyen** [comment]
C'est fait.
Par contre, le sélecteur ne s'affichage plus lorsqu'il y a plus d'une langue. Je l'intégrerai de nouveau lors d'une prochaine mise à jour.
