### ISSUE TITLE
Gérer l'outdoor

### ISSUE THREAD

**Issue by bastyen** [GeotrekCE/Geotrek-rando-widget#61]
- [x] Gestion des sites
- [x] Gestion des parcours
- [x] Le point d'entrée est un site outdoor
- [x] Prise en compte des niveaux hiérarchiques de contenus
- [x] Prises en compte des nombreux attributs, des cotations multiples
- [x] Reproduire les mécanismes de filtres existants sur Geotrek-Rando actuellement

Voir ce ticket pour des améliorations possibles : https://github.com/GeotrekCE/Geotrek-rando-v3/issues/542

**Comment by bruhnild** [comment]
**Premiers retours suite à la recette intermédiaire du widget avec la gestion des activités outdoor**

URL de test : https://test-rando-widget.geotrek.fr

## MVP

### Général

### Vue liste + carte

- [ ] Au survol d'une vignette pas de mise en évidence du picto de l'activité sur la carte
- [ ] Corriger le bug d'affichage qui survient lorsqu'on change de segment avant qu'il ait terminé de recharher tous les objets
- [ ] 

    <details>
      <summary>capture d'écran</summary>

![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/26433045/7f9349c1-f2fb-4d33-8f54-c42968b9e709)

    </details>



### Filtres

### Fiche détail + carte

- [ ] Afficher les vignettes des POI, contenus et évènements touristiques quand disponibles

- [ ] éléments manquants sur la carte :
  - le sélecteur de couches supplémentaires (contenus/évènements, lieux de renseignement, poi...) 
  - les pictos des couches secondaires 

- [ ] enlever les géométries cliquables sur la carte ([exemple](https://test-rando-widget.geotrek.fr/?outdoorsite=100))

## Amélioration futures

### Filtres

- [ ] ajout de nouveaux filtres (filière, thèmes, orientation, vent..)
- [ ] faire une distinction visuelle lorsqu'il y a un filtre actif (afficher le nombre d'éléments filtrés sur la totalité). Ceci est valable pour tous les objets et pas uniquement pour l'outdoor.

### Fiche détail + carte

- [ ] afficher les informations suivantes (orientation, vent)  dans la présentation

**Comment by babastienne** [comment]
- [ ] Il manque les sources en bas de fiche ([exemple](https://www.rando-serreponcon.com/outdoor-site/51-Aiguilles-de-Chabrieres))
- [ ] Il manque les informations "En savoir plus" ([exemple](https://www.rando-serreponcon.com/outdoor-site/51-Aiguilles-de-Chabrieres))
- [ ] Les swiper-bullets ne sont pas centrées sur les POI, touristicContent, touristicEvents (valable aussi sur les autres objets, pas que l'outdoor)
- [ ] Il manque les text d'accessibilité
- [ ] Il manque la section "Acces"

**Comment by bastyen** [comment]
- [ ] Menu sur les fiches
- [ ] Hors ligne

**Comment by bastyen** [comment]
Il n'y a pas l'information d'accès de disponible
