### ISSUE TITLE
Surcharge du style

### ISSUE THREAD

**Issue by bastyen** [GeotrekCE/Geotrek-rando-widget#62]
Pouvoir paramétrer les styles du widget de manière beaucoup plus fine.

- [x] Ajout d'un paramètre pour choisir si on souhaite des bords arrondis ou non ([commit](https://github.com/GeotrekCE/Geotrek-rando-widget/commit/ef653b54331243f10e1feb7f44c8b1ed4a7a457f))
- [x] Ajout d'un paramètre pour choisir la police ([commit](https://github.com/GeotrekCE/Geotrek-rando-widget/commit/24587e392a7a206b6f133016ff50c219311ae78d))
- [x] Donner la possibilité de surcharger via une feuille de style CSS le style complet des composants du widget.
- [x] Documenter les nouvelles possibilités de surcharges, comment paramétrer le widget avec une feuille de style externe, etc.

**Comment by bastyen** [comment]
2b2aec29c7c2542e4b7c62fd7c3a995f9fd89eca

**Comment by babastienne** [comment]
Reste à faire : 
- [ ] Gérer la surcharge de style de certains composants sur le carte (popup, pin)
