### ISSUE TITLE
Ajouter des filtres pour pouvoir limiter les résultats dans la vue Liste

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-widget#7]
A minima les filtres suivants :
- Activité
- Difficulté

**Comment by camillemonchicourt** [comment]
Le plus essentiel et demandé est le filtre par pratique.
C'est d'ailleurs celui de premier niveau dans Geotrek-rando-v3 : 
![Capture d’écran de 2022-07-05 07-56-48](https://user-images.githubusercontent.com/4418840/177259322-78947d75-0fed-464a-8fbf-e1744791db3e.png)

**Comment by bastyen** [comment]
Le filtre par pratique est, maintenant, disponible.
On en rajoutera par la suite.
