### ISSUE TITLE
Explications sur les couleurs ?

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-widget#74]
J'ai l'impression que la couleur `colorSurfaceVariant` ne sert à rien dans l'appli ?

Serait-il possible d'avoir des captures d'écran des différents écrans des annotations pour identifier les couleurs associées ? Il y a beaucoup de paramètres différents et très franchement c'est difficile de distinguer quel paramètre sert à quoi je trouve.

A chaque fois que je me retrouve à paramétrer un widget pour un territoire je passe un temps fou à essayer de paramétrer tant bien que mal en tâtonnant pour tester des combinaisons ...

**Comment by bastyen** [comment]
Actuellement, color-surface-variant définie la couleur de fond des marqueurs des étapes des itinérances sur la carte.

Je pense qu'avec la future documentation, il sera plus facile de gérer les couleurs pour chaque composant.

**Comment by bastyen** [comment]
https://geotrek-rando-widget.readthedocs.io/latest/documentation/theme/colors.html
