### ISSUE TITLE
Pictogrammes "pratique de randonnées"

### ISSUE THREAD

**Issue by MatthieuClemot** [GeotrekCE/Geotrek-rando-widget#78]
Serait-il possible de transformer les pictogrammes vers une forme de fond arrondie plutôt que carré, à l'instar du site public (cf photos ci joint)
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/149701358/fafabfe6-a788-4b0d-aa77-134f8889a675)
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/149701358/e7d46041-3115-44a5-bba8-b80225d17fb8)

**Comment by MatthieuClemot** [comment]
Pareil pour les titres de randos, à mettre sous la même forme que sur le site public (sauf si sujet déjà abordé dans un ticket que je n'aurais pas vu)
widget : 
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/149701358/605c172b-ecdf-44f4-b8b1-eea1d8eb9d39)
site public : 
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/149701358/61e6f216-0e7d-4673-bf0c-2213f5f7144b)

**Comment by bastyen** [comment]
487a7c5d449a32e138c7e936d7c68005663aec44
