### ISSUE TITLE
rectangles thématiques

### ISSUE THREAD

**Issue by MatthieuClemot** [GeotrekCE/Geotrek-rando-widget#79]
A l'instar de la demande pour les pictogrammes "pratiques", faire évoluer les rectangles "thématiques" vers une forme plus arrondies comme sur le site public et faire correspondre au maximum les couleurs
widget : 
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/149701358/2b2b01e4-bc86-46c5-8ce7-6018d8ba3039)
site public : 
![image](https://github.com/GeotrekCE/Geotrek-rando-widget/assets/149701358/efaa43c5-cfb2-42b6-88a2-9afdd13d5cb6)

**Comment by babastienne** [comment]
Sujet abordé dans la liste des retours relatifs à la recette #58

**Comment by bastyen** [comment]
487a7c5d449a32e138c7e936d7c68005663aec44
