### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-widget#82]
Add file with changelog and updates sorted by release.

This file should be listed in the documentation as well.

You can take copy the style of the changelog used in [geotrek-admin](https://github.com/GeotrekCE/Geotrek-admin/blob/master/docs/changelog.rst) or [geotrek-rando-v3](https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/changelog.md).

It should list new features, breaking changes, updates in configuration, enhancements, bugfix, maintenance, etc.

Each new pull request should update the changelog accordingly with the modifications.

**Comment by bastyen** [comment]
ce21944fac44574d751a7bb808c14ffdd609f430

**Comment by babastienne** [comment]
Can you explain more the procedure ? Where is the changelog, how can we maintain it ?

**Comment by babastienne** [comment]
Ok I think I get it now. So each time you want to do a release you'll need to open a PR like #85 ?

**Comment by bastyen** [comment]
When i will merge this PR, a release will be created. This action handle the versioning based on commits. 
> - fix: which represents bug fixes, and correlates to a [SemVer](https://semver.org/) patch.
> - feat: which represents a new feature, and correlates to a SemVer minor.
> - feat!:, or fix!:, refactor!:, etc., which represent a breaking change (indicated by the !) and will result in a SemVer major.

Then a new PR will be created automatically by this action when there will be a new commit.
