### ISSUE TITLE
Problèmes de doublon (Remontées Tourinsoft)

### ISSUE THREAD

**Issue by OTtourainenatureCrystal** [GeotrekCE/Geotrek-rando-widget#86]
Certains services, contenus touristiques, ou encore événements touristiques remontent en double ou triple sur le widget et sur le site web. 
Exemples : 
- L'hébergement L'orée des bois (contenu touristique)
- Aire de pique-nique du Val Joyeux (service)
- "L'école des chevaliers" (événement)

Est-ce que cela vient d'un souci avec Tourinsoft ou non ?

Crystal, Office de Tourisme Touraine Nature (Langeais, Bourgueil)

**Comment by babastienne** [comment]
Bonjour,

Pouvez-vous nous donner le lien vers votre widget qu'on puisse regarder ?

**Comment by OTtourainenatureCrystal** [comment]
https://demo-rando-widget.geotrek.fr/pnrlat.html

**Comment by babastienne** [comment]
Oui en effet, le problème vient des flux de données intégrés, pas du widget.

En regardant par exemple l'Orée du Bois, je trouve 6 fois la fiche, parfois avec des descriptions différentes. En investiguant j'observe que les 6 exemplaire sont issus de 6 flux de données différents : 
- Azay Chinon Geotrek - Chambres d'hôtes 
- Langeais Geotrek - Chambres d'hôtes 
- Azay Chinon Geotrek - Meublés 
- Langeais Geotrek - Meublés 
- Azay Chinon Geotrek - Hébergements insolites
- Langeais Geotrek - Hébergements insolites 

Il y a donc un  travail à faire du côté des flux communiqués pour éviter d'envoyer plusieurs fois la même fiche. 

Côté Geotrek on pourrait mettre un mécanisme en place pou éviter les doublons mais sur quel champ doit-on se baser ? Car parfois les descriptions sont différentes, les identifiants également. Et si on choisi de n'en garder qu'un ce sera arbitraire, alors dans quelle catégorie le mettre (chambre d'hotes, meublé ou hébergement insolite) ? Le plus propre serait de travailler la donnée en amont (et donc paramétrer les flux pour ne pas retourner plusieurs fois les données) plutôt que d'obliger Geotrek à faire des choix arbitraires qui risquent de ne pas vous convenir. 

A votre dispo si besoin pour échanger sur le sujet.

**Comment by OTtourainenatureCrystal** [comment]
Bonjour,
Je saisis mieux le problème en effet. Mais effectivement celà me semble compliqué à gérer. Cela me semble compliqué de faire un choix. Surtout que ce choix ne sera pas forcément applicable pour toutes les données qui remontent de Tourinsoft, cela demanderait un travail de fourmi. De notre côté, sur Tourinsoft, nous n'avons pas le choix donc ne pouvons rien modifier. A voir avec les autres territoires également comment cela remonte. Le principal, c'est que ça remonte déjà. Merci pour la réponse
