### ISSUE TITLE
Prise en compte des attributs 'portal' dans la génération de PDF

### ISSUE THREAD

**Issue by babastienne** [GeotrekCE/Geotrek-rando-widget#89]
Sur Geotrek-Rando, lorsqu'un filtre `portal=x` est activé dans la configuration pour filtrer les résultats, alors le queryparam `?portal=x` est ajouté à la requête effectuée pour récupérer le fichier PDF d'un itinéraire. Cela permet d’avoir des modèles de PDF personnalisés par portail.

Il faudrait ajouter ce comportement dans le widget pour rendre homogène le comportement entre Rando et Widget.

Exemples de PDF personnalisé par portail : 
- https://geotrek-admin.ecrins-parcnational.fr/api/fr/treks/903311/le-refuge-du-pelvoux.pdf?portal=1
- https://geotrek-admin.ecrins-parcnational.fr/api/fr/treks/903311/le-refuge-du-pelvoux.pdf?portal=2
- https://geotrek-admin.ecrins-parcnational.fr/api/fr/treks/903311/le-refuge-du-pelvoux.pdf?portal=4

**Comment by bastyen** [comment]
Et s'il y a plusieurs portals ? Prendre en compte le premier ou ne pas ajouter le paramètre portal ?

**Comment by camillemonchicourt** [comment]
L'API prévoit de pouvoir passer plusieurs portails, mais ça c'est pour de la diffusion de donnée, des passerelles, etc.

Pour GTR3 ou GTRW, cela n'a pas de sens de passer plusieurs portails en filtre de l'API, on pourrait mettre le bloquer dans la custo pour éviter des effets de bord, même si l'API le permet à juste titre.

C'est discuté ici - https://github.com/GeotrekCE/Geotrek-admin/issues/2691#issuecomment-1089093652

**Comment by camillemonchicourt** [comment]
Ouais OK.

**Comment by bastyen** [comment]
C'est fait
